sudo: required
services:
    - docker

before_install:
  - docker build -t ledons/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ledons/react-test npm test 

after_success:
  - docker build -t ledons/multi-client ./client
  - docker build -t ledons/multi-nginx ./nginx
  - docker build -t ledons/multi-server ./server
  - docker build -t ledons/multi-worker ./worker


 # Log in to docker CLI
 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
 
  # Take those images and push them to Docker hub

  - docker push ledons/multi-client
  - docker push ledons/multi-nginx
  - docker push ledons/multi-server
  - docker push ledons/multi-worker


    
